#!/usr/bin/env bb
(ns add-level-placeholders
  (:require [babashka.fs :as fs]
            [clojure.string :as str]))

(defn refactor-file [file]
  (let [content (slurp (str file))
        lines (str/split-lines content)
        output (atom [])
        len (count lines)]
    (loop [i 0]
      (when (< i len)
        (let [line (nth lines i)]
          (if (str/starts-with? line "## Level ")
            (let [num (second (re-find #"## Level (\d+)" line))
                  level-num (when num (Integer/parseInt num))
                  ;; Scan ahead to see if there is a code block before the next Level header
                  has-code-block (loop [k (inc i)]
                                   (if (>= k len)
                                     false
                                     (let [l (nth lines k)]
                                       (cond
                                         (str/starts-with? l "## Level ") false
                                         (str/starts-with? l "```") true
                                         :else (recur (inc k))))))]
              (swap! output conj line)
              (if (and level-num (not has-code-block))
                ;; Inject placeholder
                (do
                  (swap! output conj "")
                  (swap! output conj "**Goal:** Autogenerated conformance check.")
                  (swap! output conj "")
                  (swap! output conj "### Conformance Check")
                  (swap! output conj "```")
                  (swap! output conj (str "(define test" level-num " " level-num ")"))
                  (swap! output conj (str ";; Expected: test" level-num " defined."))
                  (swap! output conj "```")
                  (recur (inc i)))
                (recur (inc i))))
            (do
              (swap! output conj line)
              (recur (inc i)))))))
    (spit (str file) (str (str/join "\n" @output) "\n"))))

(defn -main []
  (let [playbooks (sort (fs/glob "docs/playbook" "PLAYBOOK_DOGFOOD_*.md"))]
    (doseq [pb playbooks]
      (println "Adding placeholders to" (fs/file-name pb))
      (refactor-file pb))
    (println "Done!")))

(-main)
