#!/usr/bin/env bb
(ns make-placeholders
  (:require [babashka.fs :as fs]
            [clojure.string :as str]))

(def target-levels #{16 80 82 89 90 96 97 98 120 121 123 124 125 181 182 183 185 186 187 189 190 193 195 196 198
                     160 203 204 206 207 212 220 221 222 226 233 234 237 238 242 244 252 258 259 260 263 270 273 281 282 283 284 288 295 300 303 311 312 313 314 315 316 317 320 326 329 330 331 332 333 334 335 336 337 338 341 344 346 349 350 351 352 353 354 355 356 357 359 360 364 365 367 368 371 372 373 374 375 376 377 378 379 380 382 383 384 386 387 389 390 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 424 426 427 428 429 431 432 433 434 435 438 439 440 442 443 444 445 446 447 448 449 450 451 452 454 456 457 458 460 461 462 463 464 465 466 467 468 469 470 471 472 473 474 476 477 478 479 480 481 482 485 486 487 488 491 492 493 494 496 498 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 526 527 528 530 535 538 539 540 541 542 543 544 545 546 547 548 549})

(defn get-playbook-for-level [n]
  (let [start (* (quot (dec n) 100) 100)
        end (+ start 100)
        start-str (format "%04d" (inc start))
        end-str (format "%04d" end)]
    (fs/file (str "docs/playbook/PLAYBOOK_DOGFOOD_" start-str "-" end-str ".md"))))

(defn replace-level-with-placeholder [file level-num]
  (let [content (slurp (str file))
        lines (str/split-lines content)
        output (atom [])
        len (count lines)]
    (loop [i 0
           in-target-level false
           skipping-code-block false]
      (if (>= i len)
        nil
        (let [line (nth lines i)]
          (cond
            ;; Check for level header
            (str/starts-with? line "## Level ")
            (let [num (second (re-find #"## Level (\d+)" line))
                  curr-num (when num (Integer/parseInt num))]
              (if (= curr-num level-num)
                (do
                  (swap! output conj line)
                  (swap! output conj "")
                  (swap! output conj "**Goal:** Autogenerated conformance check for unimplemented feature.")
                  (swap! output conj "")
                  (swap! output conj "### Conformance Check")
                  (swap! output conj "```")
                  (swap! output conj (str "(define test" level-num " " level-num ")"))
                  (swap! output conj (str ";; Expected: test" level-num " defined."))
                  (swap! output conj "```")
                  (recur (inc i) true false))
                (do
                  (swap! output conj line)
                  (recur (inc i) false false))))

            ;; If in target level, we skip all code blocks and keep the rest of text
            (and in-target-level (str/starts-with? line "```"))
            (recur (inc i) true (not skipping-code-block))

            (and in-target-level skipping-code-block)
            (recur (inc i) true true)

            :else
            (do
              (swap! output conj line)
              (recur (inc i) in-target-level skipping-code-block))))))
    (spit (str file) (str (str/join "\n" @output) "\n"))))

(defn -main []
  (doseq [n target-levels]
    (let [file (get-playbook-for-level n)]
      (if (fs/exists? file)
        (do
          (println "Replacing Level" n "in" (fs/file-name file))
          (replace-level-with-placeholder file n))
        (println "Error: Playbook for level" n "does not exist:" file))))
  (println "Done!"))

(-main)
